### ISSUE TITLE
Яндекс Музыка обновили приложение, кажется больше не будет работать.

### ISSUE THREAD

**Issue by sinedsem** [MIMBOL228/YandexMusicAppObsPreview#2]

**Comment by MIMBOL22** [comment]
Новое приложение до сих пор в бете. С новым я практически разобрался. Конечно, с ним будет на разряд труднее, но еще возможно. Моё приложение всё еще работает с (на данный момент) стабильной версией приложения (не той, которая в бете)

**Comment by sinedsem** [comment]
Не подскажете, где можно сейчас старое приложение скачать?
