### ISSUE TITLE
Не находит приложенеи яндекс музыки

### ISSUE THREAD

**Issue by SeriousX** [MIMBOL228/YandexMusicAppObsPreview#3]
[Error: ENOENT: no such file or directory, lstat 'C:\Users\Администратор\AppData\Local\Packages\A025C540.Yandex.Music_vfvw9svesycw6\LocalCache\Logs'] {
  errno: ←[33m-4058←[39m,
  code: ←[32m'ENOENT'←[39m,
  syscall: ←[32m'lstat'←[39m,
  path: ←[32m'C:\\Users\\Администратор\\AppData\\Local\\Packages\\A025C540.Yandex.Music_vfvw9svesycw6\\LocalCache\\Logs'←[39m
}

Node.js v18.13.0
Для продолжения нажмите любую клавишу . . .

По данному пути нет яндекс музыки. Оно ставится в C:\Users\Администратор\AppData\Local\Programs\YandexMusic

**Comment by MIMBOL22** [comment]
Обновлён README.md
Скрипт НЕ работает с бета-приложением Яндекс Музыки
